#!/bin/bash

#testing git hooks
#source:
#https://gist.github.com/leocaseiro/be1e82ebd68edf18f613433a68861672

while IFS='' read -r line || [[ -n "$line" ]]; do
	# if substring == # char then skip it
	if [ "${line:0:1}" == "#" ]; then
		continue
	fi
	if [ ${#line} -le 10 ]; then
		echo "Please enter a message with a least 10 characters."
		echo "Your commit message has only ${#line} characters."
		echo "Commit message you entered: ${line}"
		exit 1
	fi
done < "${1}"
exit 0